/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesign;

import Model.City;
import Model.Community;
import Model.House;
import Model.Patient;
import Model.PatientDirectory;
import Model.Person;
import Model.PersonDirectory;
import Model.SystemPeople;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vachanabelgavi
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    PersonDirectory person;
    PatientDirectory patient;
    House house;
    Community community;
    City city;
    SystemPeople system;
    
    DefaultTableModel modelTable, model;
    City selectedCity;
    
    public UpdateJPanel(PersonDirectory person, PatientDirectory patient, House house, Community community, City city, SystemPeople system) {
        initComponents();
        
        this.person = person;
        this.patient = patient;
        this.house = house;
        this.community = community;
        this.city = city;
        this.system = system;
        
        DisplayPeople();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUpdate = new javax.swing.JTable();
        txtAge = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblStreet = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        lblComm = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        lblHouse = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        jLabel1.setBackground(new java.awt.Color(54, 33, 89));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        tableUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person Name", "Age", "House Number", "Street", "Zipcode", "Community"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUpdate.setSelectionBackground(new java.awt.Color(54, 33, 89));
        jScrollPane1.setViewportView(tableUpdate);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(54, 33, 89));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ImagesFolder/update-file-20.png"))); // NOI18N
        btnSave.setText("Update");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        lblAge.setText("Age");

        btnUpdate.setBackground(new java.awt.Color(54, 33, 89));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ImagesFolder/view-20 2.png"))); // NOI18N
        btnUpdate.setText("View");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(54, 33, 89));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ImagesFolder/delete-bin-20.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblStreet.setText("Street");

        lblZip.setText("Zip Code");

        lblComm.setText("Community");

        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });

        lblHouse.setText("House Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStreet)
                            .addComponent(lblHouse)
                            .addComponent(lblZip)
                            .addComponent(lblComm))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNum)
                            .addComponent(txtStreet)
                            .addComponent(txtZip)
                            .addComponent(txtCommunity)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAge)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName)
                    .addComponent(btnUpdate))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHouse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreet)
                            .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZip)
                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblComm)
                            .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(btnSave)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here: 
        
        String name = txtName.getText();
        int age = Integer.parseInt(txtAge.getText());
        String houseNumber = txtNum.getText();
        String street = txtStreet.getText();
        String zip = txtZip.getText();
        String commun = txtCommunity.getText();
        //String ci = txtCity.getText();
        
/*

        house.setHouseNumber(houseNumber);
        house.setStreetName(street);
        house.setZipCode(zip);
        
        community.setName(commun);
        city.setCity(ci);
        
        community.addHouseToCommunity(house);
        city.addCommunityToCity(community);
        system.addCityToSystemPeople(city);
        */

        int i = tableUpdate.getSelectedRow();
        if(i >= 0){
        String initName = modelTable.getValueAt(i, 0).toString();
        int initAge = Integer.parseInt(modelTable.getValueAt(i, 1).toString());
            
                    boolean found = false;
        
        for(Person p : person.getPersonDirectory()){
            if(p.getName().equalsIgnoreCase(initName) && p.getAge()==initAge){
                found = true;
            }
        }
        
        System.out.println("Found "+found);
        
        boolean inPatientList = false;
        
            
        for(Community c : city.getCommunityList()){
            
            for(int m = 0; m < c.getHouseList().size(); m++){

                for(int j=0; j < c.getHouseList().get(m).getPersonList().size(); j++){
                    
                        if (c.getHouseList().get(m).getPersonList().get(j).getName().equals(initName) &&
                                c.getHouseList().get(m).getPersonList().get(j).getAge() == initAge) {
                            System.out.println("inPatient List " + inPatientList);
                                                    inPatientList = true;
                                                    
                                   c.getHouseList().get(m).getPersonList().get(j).setName(name);
                                   c.getHouseList().get(m).getPersonList().get(j).setAge(age);
                                   
                                   c.getHouseList().get(m).getPatientList().get(j).setName(name);
                                   c.getHouseList().get(m).getPatientList().get(j).setAge(age);
                        }
                    }
                }
            }
            
            
            modelTable.setValueAt(name, i, 0);
            modelTable.setValueAt(age, i, 1);
            modelTable.setValueAt(houseNumber, i, 2);
            modelTable.setValueAt(street, i, 3);
            modelTable.setValueAt(zip, i, 4);              
            modelTable.setValueAt(commun, i, 5);
            //modelTable.setValueAt(ci, i, 6);
        }
        else {
            System.out.println("Update error.");
        }
        
        JOptionPane.showMessageDialog(this, "Person Data Updated.");
        
        txtName.setText("");
        txtAge.setText("");
        txtNum.setText("");
        txtStreet.setText("");
        txtZip.setText("");
        txtCommunity.setText("");
        //txtCity.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tableUpdate.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }
        
        modelTable = (DefaultTableModel) tableUpdate.getModel();
        /*
        selectedCity = (City) modelTable.getValueAt(selectedRowIndex, 0);
        
        for(City c : system.getCityList()){
            //txtCity.setText(selectedCity.getCity());
            
            for(int i=0; i < c.getCommunityList().size(); i++){
                txtCommunity.setText(selectedCity.getCommunityList().get(i).getName());
                
                for(int j=0; j < c.getCommunityList().get(i).getHouseList().size(); j++){
                    txtNum.setText(selectedCity.getCommunityList().get(i).getHouseList().get(j).getHouseNumber());
                    txtStreet.setText(selectedCity.getCommunityList().get(i).getHouseList().get(j).getStreetName());
                    txtZip.setText(selectedCity.getCommunityList().get(i).getHouseList().get(j).getZipCode());
                    
                    for(int k=0; k < c.getCommunityList().get(i).getHouseList().size(); k++){
                        txtName.setText(selectedCity.getCommunityList().get(i).getHouseList().get(j).getPersonList().get(k).getName());
                        txtAge.setText(String.valueOf(selectedCity.getCommunityList().get(i).getHouseList().get(j).getPersonList().get(k).getAge()));
                    }
                }
            }
        }
        */
        
        txtName.setText(modelTable.getValueAt(selectedRowIndex, 0).toString());
        txtAge.setText(modelTable.getValueAt(selectedRowIndex, 1).toString());
        txtNum.setText(modelTable.getValueAt(selectedRowIndex, 2).toString());
        txtStreet.setText(modelTable.getValueAt(selectedRowIndex, 3).toString());
        txtZip.setText(modelTable.getValueAt(selectedRowIndex, 4).toString());
        txtCommunity.setText(modelTable.getValueAt(selectedRowIndex, 5).toString());
        //txtCity.setText(modelTable.getValueAt(selectedRowIndex, 6).toString());
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tableUpdate.getSelectedRow();
                modelTable = (DefaultTableModel) tableUpdate.getModel();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
                
        String name = modelTable.getValueAt(selectedRowIndex, 0).toString();
        
        System.out.println(name);
                System.out.println(modelTable.getValueAt(selectedRowIndex, 0).toString());

        
        //house.deleteData(per);
        //JOptionPane.showMessageDialog(this, "Person data deleted");
        
        for(Community c : city.getCommunityList()){
            
            for(int i=0; i < c.getHouseList().size(); i++){
                
                for(int j=0; j < c.getHouseList().get(i).getPersonList().size(); j++){
                    
                    
                    if(c.getHouseList().get(i).getPersonList().get(j).getName().equals(name)){
                        c.getHouseList().get(i).deletePerson(c.getHouseList().get(i).getPersonList().get(j));
                        c.getHouseList().get(i).deletePatient(c.getHouseList().get(i).getPatientList().get(j));

                    }
                   
                }
            }
        
        }
        //modelDelete.removeRow(selectedRowIndex);
        DisplayPeople();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked

    }//GEN-LAST:event_btnDeleteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblComm;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTable tableUpdate;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables


    public void DisplayPeople(){
        DefaultTableModel model = (DefaultTableModel) tableUpdate.getModel();
        model.setRowCount(0);
        System.out.println("labcd");
        Object[] list = new Object[6];
        
            for(Community c : city.getCommunityList()){
                list[5] = c.getName();
                System.out.println(list[5]);
                for(int j=0; j < c.getHouseList().size(); j++){
                    list[2] = c.getHouseList().get(j).getHouseNumber();
                    list[3] = c.getHouseList().get(j).getStreetName();
                    list[4] = c.getHouseList().get(j).getZipCode();
                    
                    for(int k=0; k < c.getHouseList().get(j).getPersonList().size(); k++){
                        list[0] = c.getHouseList().get(j).getPersonList().get(k).getName();
                        list[1] = c.getHouseList().get(j).getPersonList().get(k).getAge();
                        
                        model.addRow(list);
                    }
                }
            }
        }
        
              
}
