/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModelUI;

import ModelArray.Car;
import ModelArray.CarsList;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author vachanabelgavi
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    

    CarsList cars;
    DateFormat df;

    
    public CreateJPanel(CarsList cars) {
        initComponents();
        this.cars = cars;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblCertificate = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        RadioBtnYes = new javax.swing.JRadioButton();
        RadioBtnNo = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        dateExpiry = new com.toedter.calendar.JDateChooser();
        dateDateSaved = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Car");

        lblSerialNumber.setText("Car Serial Number *");

        lblModel.setText("Car Model *");

        lblBrand.setText("Car Brand *");

        lblYear.setText("Year of Manufacture *");

        lblCity.setText("City *");

        lblSeats.setText("Number of Seats *");

        lblCertificate.setText("Maintenance Certificate Expiry *");

        lblAvailability.setText("Availability *");

        lblDate.setText("Date *");

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtYear.setText("0");

        txtSeats.setText("0");

        RadioBtnYes.setText("Yes");
        RadioBtnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnYesActionPerformed(evt);
            }
        });

        RadioBtnNo.setText("No");
        RadioBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnNoActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("* Required");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblYear)
                            .addComponent(lblSerialNumber)
                            .addComponent(lblModel)
                            .addComponent(lblBrand)
                            .addComponent(lblCity)
                            .addComponent(lblSeats)
                            .addComponent(lblCertificate)
                            .addComponent(lblAvailability)
                            .addComponent(lblDate))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSerialNumber)
                            .addComponent(txtSeats)
                            .addComponent(txtCity)
                            .addComponent(txtYear)
                            .addComponent(txtBrand)
                            .addComponent(txtModel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBtnYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioBtnNo))
                            .addComponent(dateExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateDateSaved, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnSave))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {RadioBtnNo, RadioBtnYes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCertificate)
                    .addComponent(dateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(RadioBtnYes)
                    .addComponent(RadioBtnNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(dateDateSaved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnSave)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {RadioBtnNo, RadioBtnYes});

    }// </editor-fold>//GEN-END:initComponents

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        df= new SimpleDateFormat("MMM dd, YYYY", Locale.getDefault());
        //System.out.println(cars);
        //System.out.println("Before Car car = cars.addCar()");
        Car car = cars.addCar();
        //System.out.println("After Car car = cars.addCar()");
        String serialNumber = txtSerialNumber.getText();
        String model = txtModel.getText();
        String brand = txtBrand.getText();
        int yearOfManufacture = 0;
        yearOfManufacture = Integer.parseInt(txtYear.getText());
        int numberOfSeats = 0;
        numberOfSeats = Integer.parseInt(txtSeats.getText());
        String city = txtCity.getText();
        Date maintenanceExpiry;
        maintenanceExpiry = dateExpiry.getDate();
        Date date;
        date = dateDateSaved.getDate();
        String availability;
        if(RadioBtnYes.isSelected())
            availability = RadioBtnYes.getText();
        else
            availability = RadioBtnNo.getText();
        
        ValidateFields();
        
        car.setSerialNumber(serialNumber);
        car.setModel(model);
        car.setBrand(brand);
        car.setYearOfManufacture(yearOfManufacture);
        car.setNumberOfSeats(numberOfSeats);
        car.setCity(city);
        car.setMaintenanceExpiry(maintenanceExpiry);
        System.out.println(car.getMaintenanceExpiry());
        car.setDate(date);
        System.out.println(car.getDate());
        //System.out.println("In create " + availability);

        car.setAvailability(availability);
        
        JOptionPane.showMessageDialog(this, "New Car added.");
        
        txtSerialNumber.setText("");
        txtModel.setText("");
        txtBrand.setText("");
        txtYear.setText("");
        txtSeats.setText("");
        txtCity.setText("");
        dateExpiry.setDate(null);
        dateDateSaved.setDate(null);
        RadioBtnYes.setSelected(false);
        RadioBtnNo.setSelected(false);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void RadioBtnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnYesActionPerformed
        // TODO add your handling code here:
        if(RadioBtnYes.isSelected())
            RadioBtnNo.setSelected(false);
    }//GEN-LAST:event_RadioBtnYesActionPerformed

    private void RadioBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnNoActionPerformed
        // TODO add your handling code here:
        if(RadioBtnNo.isSelected())
            RadioBtnYes.setSelected(false);
    }//GEN-LAST:event_RadioBtnNoActionPerformed

    public void ValidateFields(){
        
        Pattern pattern;
        //serial number
        String serialNumber = txtSerialNumber.getText();
        String serialNumberValidate = "[A-Za-z0-9]{1,}";
        pattern = Pattern.compile(serialNumberValidate);
        
        if(serialNumber.equals("") || serialNumber.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the serial number.");
        }
        else{
            if(!serialNumber.equals("") || !serialNumber.isEmpty()){
                if(!pattern.matcher(serialNumber).matches()){
                    JOptionPane.showMessageDialog(this, "Please enter the correct serial number.");
                }
            }
        }
        
        
        //Model
        String modelCar = txtModel.getText();
        String modelValidate = "[A-Za-z0-9]{1,}";
        pattern = Pattern.compile(modelValidate);
        
        if(modelCar.equals("") || modelCar.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter Car Model.");
        }
        else{
            if(!modelCar.equals("") || !modelCar.isEmpty()){
                if(!pattern.matcher(modelCar).matches()){
                    JOptionPane.showMessageDialog(this, "Please enter the correct Car Model.");
                }
            }
        }
        
        
        //Brand
        String brand = txtBrand.getText();
        String brandValidate = "[A-Z]{1,}[a-z]{1,}";
        pattern = Pattern.compile(brandValidate);
        
        if(brand.equals("") || brand.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the Car Brand.");
        }
        else{
            if(!brand.equals("") || !brand.isEmpty()){
                if(!pattern.matcher(brand).matches()){
                    JOptionPane.showMessageDialog(this, "Please enter the correct Car Brand.");
                }
            }
        }
        
        
        //year of manufacture
        String year = txtYear.getText();
        String yearValidate = "[1-2]{1,4}[0-9]{1,3}";
        pattern = Pattern.compile(yearValidate);
        
        if(year.equals("") || year.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter Year of Mannufacture.");
            year = "2021";
        }
        else{
            if(!year.equals("") || !year.isEmpty()){
                if(!pattern.matcher(year).matches()){
                    JOptionPane.showMessageDialog(this, "Please enter the four-digit year.");
                }
            }
        }
        
        
        //Seats
        String seats = txtSeats.getText();
        String seatsValidate = "[0-9]{1,2}";
        pattern = Pattern.compile(seatsValidate);
        
        if(seats.equals("") || seats.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the Car Brand.");
            seats="0";
        }
        else{
            if(!seats.equals("") || !seats.isEmpty()){
                if(!pattern.matcher(seats).matches()){
                    JOptionPane.showMessageDialog(this, "Please enter the correct Car Brand.");
                }
            }
        }
        
        
        //city
        String city = txtCity.getText();
        String cityValidate = "[A-Za-z]{2,}";
        pattern = Pattern.compile(cityValidate);
        
        if(city.equals("") || city.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the City.");
        }
        else{
            if(!city.equals("") || !city.isEmpty()){
                if(!pattern.matcher(city).matches()){
                    JOptionPane.showMessageDialog(this, "Please enter the correct City Name.");
                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioBtnNo;
    private javax.swing.JRadioButton RadioBtnYes;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser dateDateSaved;
    private com.toedter.calendar.JDateChooser dateExpiry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCertificate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
